name: Dev Workflow - Configure, Install, Build and Deploy

on:
  push:
    branches:
      - 'feature*'

jobs:
  build:
   runs-on: ubuntu-latest
    env: 
      BUCKET_NAME: cfst-3457-85f978fb6fa4358643668ce8a0-nonprodbucket-x8qtsmfrruy4
    steps:
      - name: Chekcout code
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up NodeJS
      - uses: actions/setup-node@v4
        with:
        node-version: 18
      - name: Build site-gatsby
        run: |
          npm cli 
          npm run build
      - name: Upload to S3
        run: |
          aws s3 sync . s3://${{ env.BUCKET_NAME }}/
    
